# Industry Best and Worst
This file was created and written by Alex Lue. This file will clean our data, webscrape yahoo finance for market cap of select company stock tickers. and will display multiple different plots using plotly
## 1. Cleaning our csv data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re
import numpy as np

In [2]:
# import all relevant csvs/xlxs into dataframes for analysis

#collect specific columns for each df
epa_viols_df = pd.read_csv("../datasets/epa_violations.csv", 
                           usecols=[0,1,2,3,4,5,6,25,26,28,29], index_col = 0)

scope_emis_df = pd.read_csv("../datasets/2013_-_Global_500_Emissions_and_Response_Status.csv", 
                            usecols=[0,2,4,11,12], index_col = 0)
just_co_df = pd.read_excel('../datasets/JUST Capital 2018 Company Scores.xlsx')

In [3]:
# clean our data and sort by stock ticker
epa_viol_st = epa_viols_df.dropna(subset=['Parent Company Stock Ticker'])
epa_viol_st = epa_viol_st.sort_values("Parent Company Stock Ticker")
epa_viol_st['Penalty Date'] = epa_viol_st['Penalty Date'].apply(
    lambda date: str(date)[4:6]+"/"+str(date)[6:])

#change penalties to int
epa_viol_st['Penalty Amount'] = epa_viol_st['Penalty Amount'].apply(
    lambda amt: int(re.sub('[$,]','',amt)))
epa_viol_st['Subtraction From Penalty'] = epa_viol_st['Subtraction From Penalty'].apply(
    lambda amt: int(re.sub('[$,]','',amt)))
epa_viol_st['Penalty Amount Adjusted For Eliminating Multiple Counting'] = epa_viol_st['Penalty Amount Adjusted For Eliminating Multiple Counting'].apply(
    lambda amt: int(re.sub('[$,]','',amt)))
epa_viol_st.columns = ['Parent Company','Penalty ($)','Sub From Penalty ($)', 'Penalty Amount Adjusted For Eliminating Multiple Counting ($)','Year','Date','HQ Country','HQ State','Ticker','Parent Industry']
# print(len(epa_viol_st['Parent Company Stock Ticker'].unique()))
# convert list of all tickers into a set
epa_cos_set = set(epa_viol_st['Ticker'])
# len(epa_cos_set)
epa_viol_st[:50]
# print(ope_so)

,Parent Company,Penalty ($),Sub From Penalty ($),Penalty Amount Adjusted For Eliminating Multiple Counting ($),Year,Date,HQ Country,HQ State,Ticker,Parent Industry
Company,,,,,,,,,,
ALCOA POINT COMFORT OPERATIONS,Alcoa,6250,0,6250,2009,10/31,USA,New York,AA,metals
"TIFTON ALUMINUM COMPANY, INC.",Alcoa,5000,0,5000,2000,12/20,USA,New York,AA,metals
REYNOLDS METALS ST LAWRENCE REDUCTION PLANT,Alcoa,31000,0,31000,2009,02/27,USA,New York,AA,metals
REYNOLDS METALS ST LAWRENCE REDUCTION PLANT,Alcoa,178000,0,178000,2006,08/18,USA,New York,AA,metals
REYNOLDS METALS ST LAWRENCE REDUCTION PLANT,Alcoa,20000,0,20000,2003,11/25,USA,New York,AA,metals
ALCOA ROCKDALE OPERATIONS 483310000100205,Alcoa,90000,0,90000,2006,11/03,USA,New York,AA,metals
ALCOA ROCKDALE OPERATIONS 483310000100310,Alcoa,19655,0,19655,2010,01/28,USA,New York,AA,metals
INTALCO ALUMINUM CORPORATION,Alcoa,27500,0,27500,2017,08/03,USA,New York,AA,metals
INTALCO ALUMINUM CORPORATION,Alcoa,5000,0,5000,2017,08/02,USA,New York,AA,metals
ALCOA WENATCHEE WORKS,Alcoa,22750,0,22750,2007,05/09,USA,New York,AA,metals
ALCOA - EAST,Alcoa,7500,0,7500,2009,05/22,USA,New York,AA,metals
"ALCOA, INC.",Alcoa,1631996,0,1631996,2007,02/27,USA,New York,AA,metals
ALCOA INC WENATCHEE WORKS,Alcoa,36000,0,36000,2015,07/29,USA,New York,AA,metals
ALCOA INC WENATCHEE WORKS,Alcoa,6000,0,6000,2014,08/18,USA,New York,AA,metals
ALCOA INC,Alcoa,63000,0,63000,2008,08/04,USA,New York,AA,metals
ALCOA INC WENATCHEE WORKS,Alcoa,8000,0,8000,2012,12/07,USA,New York,AA,metals
"ALUMINUM COMPANY OF AMERICA, INC. (ALCOA",Alcoa,2550000,0,2550000,2002,03/28,USA,New York,AA,metals
TIFTON ALUMINIUM,Alcoa,20954,0,20954,2007,05/22,USA,New York,AA,metals
ALUMINUM COMPANY OF AMERICA SOUTH PLANT 470090000800188,Alcoa,8000,0,8000,2011,08/10,USA,New York,AA,metals
ALUMINUM COMPANY OF AMERICA SOUTH PLANT 470090000800149,Alcoa,20000,0,20000,2008,11/21,USA,New York,AA,metals
IDEM Agreed Order ALCOA Warrick Operations,Alcoa,8750,0,8750,2015,06/03,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,181400,0,181400,2001,11/05,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,15625,0,15625,2002,02/11,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,44426,0,44426,2007,07/13,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,5075,0,5075,2007,10/04,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,96360,0,96360,2009,02/08,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,6250,0,6250,2009,10/31,USA,New York,AA,metals
REYNOLDS METALS COMPANY- LAKE CHARLES CARBON COMPANY,Alcoa,50000,0,50000,2003,12/09,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,20700,0,20700,2010,12/04,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,20700,0,20700,2010,12/04,USA,New York,AA,metals
"ALCOA, INC.",Alcoa,15413,0,15413,2000,03/03,USA,New York,AA,metals
ALUMINUM COMPANY OF AMERICA (ALCOA),Alcoa,2400000,0,2400000,2000,06/14,USA,New York,AA,metals
"ALCOA - WARRICK POWER PLT, AGC DIV OF AL 181730000200109",Alcoa,5000,0,5000,2004,03/18,USA,New York,AA,metals
Alcoa Inc,Alcoa,35900,0,35900,2007,08/23,USA,New York,AA,metals
ALCOA - WARRICK OPERATIONS 181730000700429,Alcoa,15750,0,15750,2013,02/27,USA,New York,AA,metals
ALUMINUM COMPANY OF AMERICA SOUTH PLANT 470090000800251,Alcoa,5000,0,5000,2014,08/26,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,5513,0,5513,2014,04/18,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,44426,0,44426,2007,07/13,USA,New York,AA,metals
REYNOLDS METALS ST LAWRENCE REDUCTION PLANT,Alcoa,40000,0,40000,2005,10/27,USA,New York,AA,metals
IDEM Agreed Order - ALCOA IN0001155 Effective Date 07/08/2008,Alcoa,43200,0,43200,2008,07/08,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,15625,0,15625,2002,02/11,USA,New York,AA,metals
REYNOLDS METALS CO LLC - LAKE CHARLES CARBON CO,Alcoa,50000,0,50000,2003,12/09,USA,New York,AA,metals
REYNOLDS METALS COMPANY,Alcoa,24460,0,24460,2001,01/22,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,5075,0,5075,2007,10/04,USA,New York,AA,metals
Alcoa Inc.,Alcoa,334000000,0,334000000,2003,04/09,USA,New York,AA,metals
REYNOLDS METALS COMPANY- LAKE CHARLES CARBON COMPANY,Alcoa,6500,0,6500,2018,04/13,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,20700,0,20700,2010,12/04,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,5513,0,5513,2014,04/18,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,181400,0,181400,2001,11/05,USA,New York,AA,metals
ALCOA POINT COMFORT OPERATIONS,Alcoa,96360,0,96360,2009,02/08,USA,New York,AA,metals

In [4]:
# do the same for scope_emis_df
# we need to remove the country code for comparison
scope_emis_df.columns = ['Country', 'Ticker', 'Scope 1 (metric tons CO2e)', 'Scope 2 (metric tons CO2e)']
scope_emis_df['Ticker'] = scope_emis_df['Ticker'].apply(
    lambda sym: sym.split()[0])
scope_emis_df = scope_emis_df.dropna(subset=['Scope 1 (metric tons CO2e)','Scope 2 (metric tons CO2e)'])
scope_cos_set = set(scope_emis_df['Ticker'])
print(len(scope_cos_set))
scope_emis_df[:50]

330

,Country,Ticker,Scope 1 (metric tons CO2e),Scope 2 (metric tons CO2e)
Company Name,,,,
3M Company,USA,MMM,4.540000e+06,2230000.00
ABB,Switzerland,ABBN,8.190000e+05,857000.00
Abbott Laboratories,USA,ABT,4.707810e+05,537821.00
Accenture,Ireland,ACN,9.383000e+03,224615.00
Ace Ltd.,Switzerland,ACE,1.291200e+04,39791.00
adidas AG,Germany,ADS,1.216900e+04,57551.00
"Adobe Systems, Inc.",USA,ADBE,2.744000e+03,22995.00
AFLAC Incorporated,USA,AFL,3.884000e+03,18536.00
Air Liquide,France,AI,1.127200e+07,10853000.00
"Air Products & Chemicals, Inc.",USA,APD,1.476721e+07,10563030.00
Airbus Group,Netherlands,AIR,5.811150e+05,432092.00
"Allergan, Inc.",USA,AGN,4.912800e+04,52049.00
Allianz SE,Germany,ALV,8.344300e+04,176675.00
Allstate Corporation,USA,ALL,4.079600e+04,150401.00
"Altria Group, Inc.",USA,MO,2.839260e+05,236169.00
Ambev - Cia de Bebidas das Américas,Brazil,AMBV4,7.572360e+05,235799.00
American Express,USA,AXP,2.337100e+04,142667.00
"Amgen, Inc.",USA,AMGN,1.199680e+05,286679.00
Anadarko Petroleum Corporation,USA,APC,5.056818e+06,535843.00
Anglo American,United Kingdom,AAL,8.470754e+06,9403534.00
Anheuser Busch InBev,Belgium,ABI,2.459221e+06,1588297.00
Antofagasta,United Kingdom,ANTO,6.453710e+05,1539442.00
Apache Corporation,USA,APA,1.076600e+07,1314000.00
Arcelor Mittal,Luxembourg,MT,1.581920e+08,17256000.00
Assicurazioni Generali Spa,Italy,G,1.786170e+04,47876.60
Associated British Foods,United Kingdom,ABF,2.295328e+06,1067934.00
Astellas Pharma Inc.,Japan,4503,8.593700e+04,125398.00
AstraZeneca,United Kingdom,AZN,3.408000e+05,286200.00
AT&T Inc.,USA,T,9.484410e+05,7894626.00
Atlas Copco,Sweden,ATCOA,2.946400e+04,75561.00
Australia and New Zealand Banking Group,Australia,ANZ,1.642800e+04,205462.00
"Automatic Data Processing, Inc.",USA,ADP,1.550000e+04,157100.00
Aviva,United Kingdom,AV/,2.384900e+04,75733.00
AXA Group,France,CS,5.188610e+04,119929.95
BAE Systems,United Kingdom,BA/,2.779200e+05,590760.00
Baker Hughes Incorporated,USA,BHI,5.160000e+05,425000.00
Banco Bradesco S/A,Brazil,BBDC4,4.780000e+03,30219.00
Banco do Brasil S/A,Brazil,BBAS3,7.443900e+03,54348.16
Banco Santander,Spain,SAN,3.185700e+04,342928.00
Banco Santander Brasil,Brazil,SANB3,1.579000e+04,22861.00
Bank of America,USA,BAC,1.166660e+05,1421829.00
Bank of Montreal,Canada,BMO,2.093255e+04,86853.06
Bank of Nova Scotia (Scotiabank),Canada,BNS,1.631000e+04,128052.00
Barclays,United Kingdom,BARC,4.675700e+04,786547.00
Barrick Gold Corporation,Canada,ABX,3.784180e+06,2229368.38
BASF SE,Germany,BAS,2.020800e+07,4479000.00
Baxter International Inc.,USA,BAX,3.450000e+05,445000.00
Bayer AG,Germany,BAYN,4.240000e+06,4120000.00
BBVA,Spain,BBVA,9.267000e+03,295771.00
BCE Inc.,Canada,BCE,9.915100e+04,186890.00

In [5]:
# lastly for just_co_df

#find only relevant columns which are Ticker, Name, Industry, and ENV scores
jcols = ['TICKER', 'NAME', 'JUST_IND']
for c in just_co_df.columns:
    if c.startswith('ENV'):
        jcols.append(c)
        
# #apply new columns to table
just_co_new_df = just_co_df[jcols].copy()

# #rename columns 
just_co_new_df.columns = ['Ticker', 
                  'Name', 
                  'Industry', 
                  'Total Score', 
                  'Efficiency', #Uses natural resources efficently and reduces product-related waste.
                  'Management', #Has policies and practices to protect the environment
                  'Pollution', #Minimizes pollution and cleans up any environmental damage it causes.
                  'E.Clean', #Maximizes Use of Renewable Energy
                  'E.Waste', #Reduces Solid Waste to Landfill
                  'P.GHG', #Greenhouse Gas Emissions
                  'P.Chem', #Chemical Water Discharge
                  'P.RSEI', #Toxic Chemical Emissions (Risk-Screening Environmental Indicators )
                  'M.Mgmt', #Environmental Management Systems and Disclosure
                  'M.Controversy', #Controversies in Environmental Responsibility as Reported in the Media
                  'M.Fines' #Environmental Fines
                 ]
just_co_set = set(just_co_new_df['Ticker'])
print(len(just_co_set))
just_co_new_df[:50]

890

,Ticker,Name,Industry,Total Score,Efficiency,Management,Pollution,E.Clean,E.Waste,P.GHG,P.Chem,P.RSEI,M.Mgmt,M.Controversy,M.Fines
0,MSFT,Microsoft,Software,87.08,125.00,73.98,57.19,163.62,115.67,58.57,51.70,52.77,87.14,55.01,51.10
1,INTC,Intel,Semiconductors & Equipment,79.41,103.58,73.98,56.77,54.83,125.28,57.81,51.70,52.77,87.14,55.01,51.10
2,GOOG,Alphabet,Internet,57.47,43.64,71.51,56.97,50.32,40.17,58.17,51.70,52.77,82.69,55.01,51.10
3,TXN,Texas Instruments,Semiconductors & Equipment,75.29,102.68,66.58,52.79,48.83,129.94,53.65,51.70,49.71,73.79,55.01,51.10
4,IBM,International Business Machines,Computer Services,79.71,104.36,73.98,56.87,49.47,131.82,58.12,51.70,52.64,87.14,55.01,51.10
5,NVDA,Nvidia,Semiconductors & Equipment,56.28,42.65,69.04,57.12,48.83,40.17,58.45,51.70,52.77,78.24,55.01,51.10
6,VMW,VMware,Software,76.86,103.55,66.58,57.15,49.84,130.22,58.49,51.70,52.77,73.79,55.01,51.10
7,PG,Procter & Gamble,Personal Products,72.56,103.96,55.33,55.67,49.09,131.60,56.28,51.69,52.30,69.34,39.17,51.09
8,ADBE,Adobe Systems,Software,79.87,107.15,71.51,57.05,48.84,136.62,58.32,51.70,52.77,82.69,55.01,51.10
9,CSCO,Cisco Systems,Technology Hardware,57.26,45.44,69.04,57.11,53.01,40.17,58.42,51.70,52.77,78.24,55.01,51.10
10,HUM,Humana,Health Care Providers,57.17,42.65,71.51,57.13,48.83,40.17,58.45,51.70,52.77,82.69,55.01,51.10
11,ACN,Accenture,Commercial Support Services,83.11,114.03,73.98,56.84,49.20,146.54,57.94,51.70,52.77,87.14,55.01,51.10
12,T,AT&T,Telecommunications,64.34,66.53,69.04,55.90,48.84,75.87,56.26,51.70,52.74,78.24,55.01,51.09
13,GM,General Motors,Automobiles & Parts,64.27,103.40,63.55,17.70,48.88,130.96,-11.22,51.69,50.98,69.34,54.00,51.10
14,GIS,General Mills,Food,74.19,107.01,61.06,50.55,48.83,136.41,56.64,51.69,42.67,82.69,36.16,51.10
15,AAPL,Apple,Technology Hardware,82.45,113.30,72.55,57.21,79.42,115.23,58.60,51.70,52.77,87.14,52.44,51.10
16,KMB,Kimberly Clark,Personal Products,60.31,69.76,66.57,41.13,49.34,80.21,29.45,51.70,52.77,73.79,55.01,51.09
17,RMD,ResMed,Health Care Equipment & Services,73.53,96.73,64.11,56.99,48.83,121.03,58.20,51.70,52.77,69.34,55.01,51.10
18,BIIB,Biogen,Pharmaceuticals & Biotech,86.18,125.00,71.51,57.13,781.74,116.30,58.46,51.70,52.77,82.69,55.01,51.10
19,UPS,United Parcel Service,Transportation,73.48,97.94,69.04,49.26,48.84,122.85,44.19,51.70,52.77,78.24,55.01,51.10
20,KEYS,Keysight Technologies,Industrial Goods,77.11,99.58,71.51,56.76,48.85,125.28,57.79,51.70,52.77,82.69,55.01,51.10
21,SPGI,S&P Global,Consumer & Diversified Finance,79.03,102.30,73.98,57.04,48.83,129.36,58.29,51.70,52.77,87.14,55.01,51.10
22,CL,Colgate Palmolive,Personal Products,62.02,99.36,29.61,56.62,49.41,124.40,57.54,51.70,52.77,73.79,-11.65,51.10
23,PRU,Prudential Financial,Insurance,77.06,101.57,69.04,57.19,48.83,128.27,58.57,51.70,52.77,78.24,55.01,51.10
24,CLX,Clorox,Personal Products,73.90,105.97,56.55,56.34,48.83,134.86,57.04,51.70,52.76,55.99,55.01,50.81
25,MMM,3M Co,Industrial Goods,60.79,78.31,61.08,39.18,48.84,93.49,52.77,45.28,32.35,87.14,31.76,51.08
26,UNH,UnitedHealth Group,Health Care Providers,55.01,43.99,64.11,57.20,50.84,40.17,58.58,51.70,52.77,69.34,55.01,51.10
27,A,Agilent Technologies,Industrial Goods,70.53,78.22,73.98,56.97,48.83,93.37,58.20,51.70,52.75,87.14,55.01,51.10
28,CRM,salesforce.com,Software,56.39,43.05,69.04,56.99,49.43,40.17,58.21,51.70,52.77,78.24,55.01,51.10
29,AMZN,Amazon,Retail,51.78,42.65,56.53,57.03,48.83,40.17,58.28,51.70,52.77,55.99,55.01,50.77
30,EXC,Exelon Corp,Utilities,60.18,106.30,70.96,-9.01,48.83,135.34,-59.49,51.69,50.81,82.69,55.01,50.11
31,VAR,Varian Medical Systems,Health Care Equipment & Services,56.25,42.65,69.04,57.02,48.83,40.17,58.27,51.70,52.77,78.24,55.01,51.10
32,MRK,Merck & Co,Pharmaceuticals & Biotech,64.88,66.04,73.98,52.28,48.83,75.15,51.37,51.70,51.06,87.14,55.01,51.09
33,CI,Cigna Corp,Health Care Providers,58.06,42.65,73.98,57.18,48.83,40.17,58.55,51.70,52.77,87.14,55.01,51.10
34,FB,Facebook,Internet,54.79,43.58,64.11,56.92,50.23,40.17,58.07,51.70,52.77,69.34,55.01,51.10
35,OC,Owens Corning,Building Materials & Packaging,66.48,100.07,71.29,19.81,48.83,126.03,20.60,51.70,22.97,82.69,55.01,50.69
36,F,Ford Motor,Automobiles & Parts,55.09,42.65,66.57,56.06,48.83,40.17,57.70,51.70,51.59,73.79,55.01,51.08
37,INTU,Intuit,Software,56.29,42.65,69.04,57.16,48.83,40.17,58.51,51.70,52.77,78.24,55.01,51.10
38,NKE,Nike,Household Goods & Apparel,70.44,90.08,61.92,57.12,48.83,111.10,58.44,51.70,52.77,78.24,42.15,51.10
39,NLSN,Nielsen Holdings,Media,55.39,42.65,66.58,57.09,48.83,40.17,58.38,51.70,52.77,73.79,55.01,51.10
40,JCI,Johnson Controls,Commercial Support Services,66.78,80.59,63.60,53.96,48.83,96.90,56.02,51.69,49.46,78.24,45.25,51.03
41,ADSK,Autodesk,Software,66.57,71.80,69.04,57.20,48.83,83.76,58.58,51.70,52.77,78.24,55.01,51.10
42,V,Visa,Consumer & Diversified Finance,77.35,97.43,73.98,57.14,48.83,122.09,58.48,51.70,52.77,87.14,55.01,51.10
43,VZ,Verizon Communications,Telecommunications,54.33,42.65,64.11,56.45,48.83,40.17,57.23,51.70,52.77,69.34,55.01,51.09
44,PYPL,PayPal,Commercial Support Services,51.93,42.95,56.71,56.93,49.29,40.17,58.10,51.70,52.77,55.99,55.01,51.10
45,EW,Edwards Lifesciences,Health Care Equipment & Services,66.42,68.72,73.98,54.32,49.62,78.37,57.82,51.70,48.32,87.14,55.01,51.10
46,COP,ConocoPhillips,Oil & Gas,55.52,67.25,55.36,41.48,48.83,76.96,30.11,51.70,52.74,73.79,34.78,51.09
47,XRX,Xerox,Commercial Support Services,81.18,108.78,73.98,56.57,48.84,139.05,57.82,51.41,52.68,87.14,55.01,51.10
48,CAT,Caterpillar,Commercial Vehicles & Machinery,74.93,101.69,63.66,56.33,48.83,128.45,57.13,51.60,52.75,78.24,45.29,51.09
49,BAX,Baxter International,Health Care Equipment & Services,70.06,97.27,73.98,32.24,49.97,120.71,43.67,51.70,22.43,87.14,55.01,51.10

## 2. Scrape for Market Cap

In [6]:
intersection_all_dfs = just_co_set & scope_cos_set & epa_cos_set
intersn_epa_just = epa_cos_set & just_co_set
intersn_epa_scope = scope_cos_set & epa_cos_set
intersn_just_scope = just_co_set & scope_cos_set
print("{} similar companies between all 3 datasets".format(len(intersection_all_dfs)))
print("{} similar companies between EPA Violations & Scope 1&2 Cos datasets".format(len(intersn_epa_scope)))
print("{} similar companies between EPA Violations & Just Cos datasets".format(len(intersn_epa_just)))
print("{} similar companies between Scope 1&2 Cos & Just Cos datasets".format(len(intersn_just_scope)))

84 similar companies between all 3 datasets
101 similar companies between EPA Violations & Scope 1&2 Cos datasets
373 similar companies between EPA Violations & Just Cos datasets
129 similar companies between Scope 1&2 Cos & Just Cos datasets

In [7]:
# with all 3 of these datasets combined, theres 110 stock companies that are the same!
# we will now scrape yahoo finance to get the estimated valuation of the corporation/company
# In this case, we will use the Market Cap, which helps estimate the value of a company
from bs4 import BeautifulSoup as bs
import requests
import time
url_a = 'https://finance.yahoo.com/quote/'
url_b = '/key-statistics?p='
#use AA to demo
html = requests.get(url_a+'AA'+url_b+'AA')
bs_obj = bs(html.text)
table = bs_obj.find('table',class_ = 'table-qsp-stats Mt(10px)')
trs = table.tbody.findChildren(recursive = False)

for tr in trs:
    if(tr.td.span.text == 'Market Cap (intraday)'):
        print(tr.find('td', class_ = 'Fz(s) Fw(500) Ta(end)').text)
        break

4B

In [8]:
# create a dictionary with market values and ticker
company_value = {
    "Ticker":[],
    "Company Valuation (Millions)":[]
}

# We will now automate this scrape so we can get all 84 companies 
# We will use a 1.5 sec timer between requests to not overload the server
# and then add into a dictionary to create a dataframe
for ticker in intersection_all_dfs:
    time.sleep(1.5)
    company_value['Ticker'].append(ticker)
    url = 'https://finance.yahoo.com/quote/{0}/key-statistics?p={0}'.format(ticker)
    html = requests.get(url)
    bs_obj = bs(html.text)
    table = bs_obj.find('table',class_ = 'table-qsp-stats Mt(10px)')
    trs = table.tbody.findChildren(recursive = False)
    for tr in trs:
        try:
            if(tr.td.span.text == 'Market Cap (intraday)'):
                cw = tr.find('td', class_ = 'Fz(s) Fw(500) Ta(end)').text
                # Notice we have B and M values in our cw, we need to convert to numbers
                if cw == 'N/A':
                    cw = 0
                else:
                    if cw[-1] == "M":
                        cw = float(cw[:-1])
                    elif cw[-1] == 'B':
                        cw = float(cw[:-1])*1000
                company_value['Company Valuation (Millions)'].append(cw)
                break
        except AttributeError:
            company_value['Company Valuation (Millions)'].append(np.nan)
            print(ticker)
            break

# Convert to a df
company_valuation_df = pd.DataFrame(company_value)

In [45]:
# save this as a csv to reference later if needed
company_valuation_df.to_csv("../datasets/market_cap_with_ticker.csv", index = False)

In [9]:
company_valuation_df.sort_values('Company Valuation (Millions)')

   Ticker  Company Valuation (Millions)
62     ST                        7330.0
19    CSL                        7780.0
76    NBL                        9910.0
72    DVN                       10640.0
22    APA                       10840.0
17    WDC                       11130.0
67    CTL                       11430.0
39   TSCO                       12940.0
42    AAL                       13510.0
69    FCX                       14780.0
31    HES                       16850.0
58    HAL                       18830.0
79      K                       18990.0
16    DTE                       23740.0
0     GLW                       23930.0
83    CMI                       25320.0
81    PPG                       26670.0
75    NEM                       28940.0
1     HPQ                       29610.0
10    GIS                       30740.0
70    ETN                       33130.0
29    YUM                       33170.0
40     DG                       33960.0
77    APC                       35230.0
46    CCL                       35340.0
53    JCI                       35440.0
7     SYY                       36470.0
52    OXY                       36680.0
43      F                       38900.0
64    BAX                       39210.0
..    ...                           ...
78     GE                       86510.0
59    MMM                       94950.0
71   SBUX                       98590.0
20    LMT                       99600.0
54    TXN                      103380.0
21   AMGN                      106400.0
41    LLY                      108200.0
38   COST                      110500.0
56    UTX                      113540.0
51    IBM                      117230.0
45    UNP                      120810.0
48    HON                      123910.0
15    MDT                      129380.0
44    ABT                      141290.0
74    PEP                      185010.0
11     BA                      197280.0
60   INTC                      201910.0
65    MRK                      209680.0
27     HD                      216940.0
3      KO                      219280.0
68    CVX                      229880.0
80      T                      234270.0
6     PFE                      237120.0
2      VZ                      237970.0
24    DIS                      246940.0
14     PG                      269340.0
55    WMT                      301360.0
66    XOM                      314410.0
23    JPM                      357990.0
63    JNJ                      362890.0

[84 rows x 2 columns]

In [10]:
# lets clean the epa violations so that we only have ticker, parent co, penalties, HQ Country, industry
cleaned_epa = epa_viol_st.groupby(['Ticker', 'Parent Company','HQ Country','Parent Industry']).agg(
    {'Penalty ($)':'sum'}).reset_index()
cleaned_epa[:50]

,Ticker,Parent Company,HQ Country,Parent Industry,Penalty ($)
0,AA,Alcoa,USA,metals,342221726
1,AAL,American Airlines,USA,airlines,429071
2,AAP,Advance Auto Parts,USA,retailing,20619
3,ABB,ABB Ltd.,Switzerland,utilities and power generation,175150
4,ABBV,AbbVie,USA,pharmaceuticals,130000
5,ABT,Abbott Laboratories,USA,pharmaceuticals,816056
6,ABX,Barrick Gold,Canada,mining and minerals,2114335
7,ACCO,ACCO Brands,USA,miscellaneous manufacturing,105000
8,ACET,Aceto,USA,pharmaceuticals,18100
9,ACM,AECOM,USA,construction and engineering,229102
10,ADM,Archer Daniels Midland,USA,agribusiness,360456917
11,ADSW,Advanced Disposal Services Inc.,USA,waste management and environmental services,445000
12,AEE,Ameren,USA,utilities and power generation,24054875
13,AEP,American Electric Power,USA,utilities and power generation,4690905947
14,AER,AerCap,Ireland,miscellaneous services,100000
15,AES,AES Corp.,USA,utilities and power generation,1948482
16,AFI,Armstrong Flooring,USA,building materials,80000
17,AGCO,AGCO,USA,agribusiness,148805
18,AGN,Allergan,Ireland (reincorporated for tax reasons),pharmaceuticals,150800
19,AIR,AAR Corp.,USA,aerospace and military contracting,19200
20,AJRD,Aerojet Rocketdyne,USA,aerospace and military contracting,85200
21,AKRX,Akorn Inc.,USA,pharmaceuticals,20500
22,AKS,AK Steel,USA,metals,24271533
23,ALB,Albemarle,USA,chemicals,711413
24,ALE,Allete,USA,utilities and power generation,7000000
25,ALG,Alamo Group,USA,agribusiness,5000
26,ALK,Alaska Air,USA,airlines,84500
27,ALLE,Allegion,Ireland,miscellaneous manufacturing,26600
28,AME,Ametek,USA,electrical and electronic equipment,365241
29,AMGN,Amgen,USA,pharmaceuticals,55968
30,AMID,American Midstream Partners,USA,oil and gas,70310
31,AMOT,Allied Motion Technologies,USA,miscellaneous manufacturing,39034
32,AMRC,Ameresco,USA,miscellaneous services,24000
33,AMT,American Tower Corp.,USA,miscellaneous services,40884
34,AMWD,American Woodmark,USA,building materials,73990
35,AMZN,Amazon.com,USA,retailing,11252309
36,ANDE,Andersons Inc.,USA,wholesalers,329540
37,AOBC,American Outdoor Brands,USA,miscellaneous manufacturing,116272
38,AOS,A.O. Smith,USA,miscellaneous manufacturing,16000
39,APA,Apache,USA,oil and gas,111053
40,APC,Anadarko Petroleum,USA,oil and gas,5181750562
41,APD,Air Products & Chemicals,USA,chemicals,3529664
42,APH,Amphenol,USA,electrical and electronic equipment,68234
43,APO,Apollo Global Management,USA,private equity (including portfolio companies),3776999
44,APOG,Apogee Enterprises,USA,building materials,126369
45,AR,Antero Resources,USA,oil and gas,12348538
46,ARCB,ArcBest Corp.,USA,miscellaneous services,38700
47,ARCH,Arch Coal,USA,mining and minerals,12261445
48,ARES,Ares Management,USA,private equity (including portfolio companies),409490
49,ARLP,Alliance Resource Partners,USA,mining and minerals,194500

In [11]:
# merge of epa violations and stocks merge
epa_stk_merge1 = pd.concat([cleaned_epa.set_index('Ticker'),company_valuation_df.set_index('Ticker')],
                            axis=1, join='inner').reset_index()

# merge of merge1 and scope
scope_merge1_2 = pd.merge(epa_stk_merge1, scope_emis_df[['Ticker','Scope 1 (metric tons CO2e)','Scope 2 (metric tons CO2e)']],
                         on='Ticker')

# merge of just cap and merge2
complete_merge_df = pd.merge(scope_merge1_2, just_co_new_df[['Ticker','Total Score']],
                            on='Ticker')

# Add a new column to understand relative size based off company valuation
largest_co = complete_merge_df['Company Valuation (Millions)'].max()
complete_merge_df['Relative Size'] = complete_merge_df['Company Valuation (Millions)'].apply(
    lambda val: (val/largest_co)*100)

In [12]:
complete_merge_df

,Ticker,Parent Company,HQ Country,Parent Industry,Penalty ($),Company Valuation (Millions),Scope 1 (metric tons CO2e),Scope 2 (metric tons CO2e),Total Score,Relative Size
0,AAL,American Airlines,USA,airlines,429071,13510.0,8.470754e+06,9403534.00,45.38,3.722891
1,ABT,Abbott Laboratories,USA,pharmaceuticals,816056,141290.0,4.707810e+05,537821.00,70.22,38.934663
2,AGN,Allergan,Ireland (reincorporated for tax reasons),pharmaceuticals,150800,40990.0,4.912800e+04,52049.00,75.01,11.295434
3,AMGN,Amgen,USA,pharmaceuticals,55968,106400.0,1.199680e+05,286679.00,69.65,29.320180
4,APA,Apache,USA,oil and gas,111053,10840.0,1.076600e+07,1314000.00,38.81,2.987131
5,APC,Anadarko Petroleum,USA,oil and gas,5181750562,35230.0,5.056818e+06,535843.00,35.76,9.708176
6,APD,Air Products & Chemicals,USA,chemicals,3529664,48760.0,1.476721e+07,10563030.00,40.39,13.436579
7,BA,Boeing,USA,aerospace and military contracting,601850,197280.0,5.760000e+05,998000.00,52.36,54.363581
8,BAX,Baxter International,USA,medical equipment and supplies,59455,39210.0,3.450000e+05,445000.00,70.06,10.804927
9,BK,Bank of New York Mellon,USA,financial services,15000,41960.0,9.513000e+03,208926.00,83.33,11.562733
10,BMY,Bristol-Myers Squibb,USA,pharmaceuticals,6163137,75490.0,2.697340e+05,262565.00,66.53,20.802447
11,CCL,Carnival Corp.,USA,entertainment,62000,35340.0,1.081981e+07,57585.00,47.05,9.738488
12,CELG,Celgene,USA,pharmaceuticals,6035,67130.0,1.445800e+04,18420.00,67.38,18.498719
13,CMI,Cummins,USA,miscellaneous manufacturing,32679768,25320.0,2.320520e+05,409890.00,78.28,6.977321
14,COP,ConocoPhillips,USA,oil and gas,134829633,65780.0,2.417100e+07,1638000.00,55.52,18.126705
15,COST,Costco,USA,retailing,2950402,110500.0,3.628020e+05,1197983.00,48.07,30.449999
16,CSL,Carlisle,USA,building materials,715066,7780.0,5.538300e+04,136951.00,46.25,2.143900
17,CSX,CSX,USA,railroads,5947399,62720.0,5.268905e+06,300170.00,59.29,17.283474
18,CTL,CenturyLink,USA,telecommunications,167493,11430.0,2.795225e+05,2079911.50,51.30,3.149715
19,CVS,CVS Health,USA,retailing,585165,70290.0,2.010000e+05,1495000.00,57.15,19.369506
20,CVX,Chevron,USA,oil and gas,494332869,229880.0,5.855922e+07,3849319.00,51.71,63.347020
21,DE,Deere,USA,agribusiness,826800,46440.0,4.401470e+05,1053446.00,52.20,12.797266
22,DG,Dollar General,USA,retailing,174088,33960.0,2.195535e+06,193548.00,49.17,9.358208
23,DIS,Walt Disney,USA,entertainment,33361,246940.0,8.673530e+05,899027.00,54.56,68.048169
24,DTE,DTE Energy,USA,utilities and power generation,8262002,23740.0,3.561280e+05,3291232.00,42.18,6.541927
25,DVN,Devon Energy,USA,oil and gas,154217,10640.0,7.596657e+06,1087905.00,54.19,2.932018
26,ECL,Ecolab,USA,chemicals,2488306,56720.0,3.362580e+05,199296.00,59.96,15.630081
27,ETN,Eaton,Ireland (reincorporated for tax reasons),industrial equipment,499100,33130.0,1.053820e+05,637346.00,59.45,9.129488
28,EXC,Exelon,USA,utilities and power generation,20512146,48770.0,2.603889e+07,5691542.00,60.18,13.439334
29,F,Ford Motor,USA,motor vehicles,4581355,38900.0,1.698799e+06,3440338.00,55.09,10.719502
...,...,...,...,...,...,...,...,...,...,...
55,MRK,Merck,USA,pharmaceuticals,30092729,209680.0,1.053000e+06,927000.00,64.88,57.780595
56,MS,Morgan Stanley,USA,financial services,1555000,72020.0,1.375746e+04,330746.62,57.12,19.846234
57,NBL,Noble Energy,USA,oil and gas,83773408,9910.0,2.078600e+06,61630.00,49.47,2.730855
58,NEM,Newmont Mining,USA,mining and minerals,520000,28940.0,4.016150e+06,1182740.00,30.38,7.974868
59,NSC,Norfolk Southern,USA,railroads,12146170,53160.0,4.925238e+06,252854.00,71.02,14.649067
60,OXY,Occidental Petroleum,USA,oil and gas,5052202,36680.0,1.427000e+07,5600000.00,37.17,10.107746
61,PEP,PepsiCo,USA,food products,625332,185010.0,3.854784e+06,1928490.00,54.02,50.982391
62,PFE,Pfizer,USA,pharmaceuticals,9037642,237120.0,1.217736e+06,1155762.00,63.51,65.342115
63,PG,Procter & Gamble,USA,household and personal care products,628606,269340.0,2.799000e+06,3028000.00,72.56,74.220838
64,PPG,PPG Industries,USA,chemicals,1863904,26670.0,4.053000e+06,1810000.00,42.54,7.349335
65,PRU,Prudential Financial,USA,financial services,6000,40540.0,5.090000e+03,70613.00,77.06,11.171429
66,PRU,Prudential Financial,USA,financial services,6000,40540.0,1.249960e+04,114635.67,77.06,11.171429
67,RTN,Raytheon,USA,aerospace and military contracting,101370,51390.0,1.017150e+05,435872.00,52.67,14.161316
68,SBUX,Starbucks,USA,restaurants and foodservice,20321,98590.0,2.399720e+05,792644.00,54.45,27.168012
69,SLB,Schlumberger,Netherlands,oilfield services and supplies,59238,48550.0,2.200000e+06,550000.00,64.04,13.378710
70,ST,Sensata Technologies,Netherlands,miscellaneous manufacturing,10000,7330.0,6.896520e+03,177320.68,51.71,2.019896
71,SYY,Sysco,USA,wholesalers,319027,36470.0,7.882000e+05,336857.00,50.92,10.049877
72,T,AT&T,USA,telecommunications,5395701,234270.0,9.484410e+05,7894626.00,64.34,64.556753
73,TGT,Target,USA,retailing,415505,43910.0,5.270470e+05,2489866.00,72.85,12.100085
74,TJX,TJX,USA,retailing,325325,61720.0,6.308400e+04,686955.00,55.31,17.007909
75,TSCO,Tractor Supply Co.,USA,retailing,1896700,12940.0,1.418798e+06,3764068.00,52.55,3.565819
76,TXN,Texas Instruments,USA,electrical and electronic equipment,63483,103380.0,8.272744e+05,1588465.81,75.29,28.487972
77,UNP,Union Pacific,USA,railroads,38520096,120810.0,1.159551e+07,407176.00,53.80,33.291080
78,UPS,United Parcel Service,USA,freight and logistics,141628,84350.0,1.171564e+07,823212.00,73.48,23.243958
79,UTX,United Technologies,USA,aerospace and military contracting,1188395,113540.0,8.016940e+05,880896.00,52.63,31.287718
80,VZ,Verizon Communications,USA,telecommunications,3496893,237970.0,5.128990e+05,5334874.05,54.33,65.576345
81,WDC,Western Digital,USA,electrical and electronic equipment,125000,11130.0,2.518700e+04,458569.00,49.84,3.067045
82,WMT,Walmart,USA,retailing,104248460,301360.0,5.605099e+06,15581135.00,71.51,83.044449
83,XOM,Exxon Mobil,USA,oil and gas,1011140943,314410.0,1.320000e+08,14000000.00,46.57,86.640580
84,YUM,Yum Brands,USA,restaurants and foodservice,6374,33170.0,1.565100e+05,2377372.00,54.48,9.140511

## 3. Plotly Graphs

In [16]:
import plotly.plotly as py
import plotly.graph_objs as go

# initialize var we will use 
# hover text
bubble_text = []

#for gradient of bubble
hi_scope1 = complete_merge_df['Scope 1 (metric tons CO2e)'].max()
low_scope1 = complete_merge_df['Scope 1 (metric tons CO2e)'].max()
cmpl_no_out = complete_merge_df[~complete_merge_df['Ticker'].isin(['APC','XOM', 'CVX'])]

In [17]:
# lets create a scatter plot of all our data using plotly



# this is so we can add additional information for when we hover over a bubble
bubble_text = []
for _, row in complete_merge_df.iterrows():
    bubble_text.append(('Ticker: {tick}<br>'
                       + 'Company: {co}<br>'
                       + 'Valuation: ${val}M<br>'
                       + 'Country: {hq}<br>'
                       + 'Industry: {ind}<br>'
                       + 'Scope 1: {s1}<br>'
                       + 'Scope 2: {s2}').format(tick=row['Ticker'],
                                                co=row['Parent Company'],
                                                val=row['Company Valuation (Millions)'],
                                                hq=row['HQ Country'],
                                                ind=row['Parent Industry'],
                                                s1=row['Scope 1 (metric tons CO2e)'],
                                                s2=row['Scope 2 (metric tons CO2e)']))
# add this into the dataframe as another column
complete_merge_df['text_display'] = bubble_text

# Trace 0 represents our first scatter. we define our x and y axis here as well
# as other info such as color, marker type, hover text
trace0 = go.Scatter(
    x = complete_merge_df['Total Score'],
    y = complete_merge_df['Penalty ($)'],
    mode = 'markers',
    text = complete_merge_df['text_display'],
    marker = dict(
        size = complete_merge_df['Relative Size'],
        cmin = low_scope1,
        cmax = hi_scope1,
        color = complete_merge_df['Scope 1 (metric tons CO2e)'],
        colorbar = dict(
            title = 'Scope 1 Emissions'
        ),
        colorscale='Viridis'
    )
)

# Add this into our data that our figure will read to populate the graph
data = [trace0]

# This layout will include x and y axis labels and our title
layout = go.Layout(
    title = 'Just Score vs EPA Penalty',
    xaxis=dict(
        title = 'Just Score'
    ),
    yaxis=dict(
        title = 'EPA Penalty (Dollars)'
    )
)

# plots
fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Just Score vs EPA Penalty')

In [18]:
# The top diagram is great, but we see 3 outliers, APC, XOM, and CVX.
# Let's remove these and replot

# this is so we can add additional information for when we hover over a bubble
bubble_text = []
for _, row in cmpl_no_out.iterrows():
    bubble_text.append(('Ticker: {tick}<br>'
                       + 'Company: {co}<br>'
                       + 'Valuation: ${val}M<br>'
                       + 'Country: {hq}<br>'
                       + 'Industry: {ind}<br>'
                       + 'Scope 1: {s1}<br>'
                       + 'Scope 2: {s2}').format(tick=row['Ticker'],
                                                co=row['Parent Company'],
                                                val=row['Company Valuation (Millions)'],
                                                hq=row['HQ Country'],
                                                ind=row['Parent Industry'],
                                                s1=row['Scope 1 (metric tons CO2e)'],
                                                s2=row['Scope 2 (metric tons CO2e)']))
cmpl_no_out['text_display'] = bubble_text

trace0 = go.Scatter(
    x = cmpl_no_out['Total Score'],
    y = cmpl_no_out['Penalty ($)'],
    mode = 'markers',
    text = cmpl_no_out['text_display'],
    marker = dict(
        size = cmpl_no_out['Relative Size'],
        cmin = low_scope1,
        cmax = hi_scope1,
        color = cmpl_no_out['Scope 1 (metric tons CO2e)'],
        colorbar = dict(
            title = 'Scope 1 Emissions'
        ),
        colorscale='Viridis'
    )
)

data = [trace0]

layout = go.Layout(
    title = 'Just Score vs EPA Penalty',
    xaxis=dict(
        title = 'Just Score'
    ),
    yaxis=dict(
        title = 'EPA Penalty (Dollars)'
    )
)

fig = go.Figure(data=data, layout=layout)
py.iplot(fig, filename='Just Score vs EPA Penalty no outliers')

/Users/alexlue/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [28]:
complete_merge_df.groupby("Parent Industry").count().sort_values("Ticker", ascending = False)

,Ticker,Parent Company,HQ Country,Penalty ($),Company Valuation (Millions),Scope 1 (metric tons CO2e),Scope 2 (metric tons CO2e),Total Score,Relative Size,text_display
Parent Industry,,,,,,,,,,
oil and gas,9,9,9,9,9,9,9,9,9,9
retailing,9,9,9,9,9,9,9,9,9,9
pharmaceuticals,9,9,9,9,9,9,9,9,9,9
financial services,5,5,5,5,5,5,5,5,5,5
aerospace and military contracting,4,4,4,4,4,4,4,4,4,4
food products,4,4,4,4,4,4,4,4,4,4
miscellaneous manufacturing,4,4,4,4,4,4,4,4,4,4
electrical and electronic equipment,4,4,4,4,4,4,4,4,4,4
railroads,3,3,3,3,3,3,3,3,3,3
telecommunications,3,3,3,3,3,3,3,3,3,3
chemicals,3,3,3,3,3,3,3,3,3,3
oilfield services and supplies,2,2,2,2,2,2,2,2,2,2
entertainment,2,2,2,2,2,2,2,2,2,2
restaurants and foodservice,2,2,2,2,2,2,2,2,2,2
household and personal care products,2,2,2,2,2,2,2,2,2,2
diversified,2,2,2,2,2,2,2,2,2,2
utilities and power generation,2,2,2,2,2,2,2,2,2,2
medical equipment and supplies,2,2,2,2,2,2,2,2,2,2
mining and minerals,2,2,2,2,2,2,2,2,2,2
motor vehicles,2,2,2,2,2,2,2,2,2,2
freight and logistics,2,2,2,2,2,2,2,2,2,2
industrial equipment,1,1,1,1,1,1,1,1,1,1
information technology,1,1,1,1,1,1,1,1,1,1
agribusiness,1,1,1,1,1,1,1,1,1,1
building materials,1,1,1,1,1,1,1,1,1,1
beverages,1,1,1,1,1,1,1,1,1,1
automotive parts,1,1,1,1,1,1,1,1,1,1
airlines,1,1,1,1,1,1,1,1,1,1
wholesalers,1,1,1,1,1,1,1,1,1,1

In [36]:
# take a look at different industries. So lets create this as a function so we can reuse code
def plotly_fig(df, industry, ttl):
    trace0 = go.Scatter(
        x = df['Total Score'][df['Parent Industry'] == industry],
        y = df['Penalty ($)'][df['Parent Industry'] == industry],
        mode = 'markers',
        text = df['text_display'][df['Parent Industry'] == industry],
        marker = dict(
            size = df['Relative Size'][df['Parent Industry'] == industry],
            cmin = low_scope1,
            cmax = hi_scope1,
            color = df['Scope 1 (metric tons CO2e)'][df['Parent Industry'] == industry],
            colorbar = dict(
                title = 'Scope 1 Emissions'
            ),
            colorscale='Viridis'
        )
    )

    data = [trace0]

    layout = go.Layout(
        title = 'Just Score vs EPA Penalty by Industry: ' + ttl,
        xaxis=dict(
            title = 'Just Score'
        ),
        yaxis=dict(
            title = 'EPA Penalty (Dollars)'
        )
    )
    return go.Figure(data=data, layout=layout)

In [37]:
# Take a look at pharma, oil&gas, retailing, financial services
fig_pharma = plotly_fig(complete_merge_df, "pharmaceuticals", "Pharmaceuticals")
py.iplot(fig_pharma, filename='Just Score vs EPA Penalty Pharmaceuticals')

In [41]:
fig_oilgas = plotly_fig(complete_merge_df, "oil and gas", 'Oil & Gas')
py.iplot(fig_oilgas, filename='Just Score vs EPA Penalty Oil & Gas')

In [42]:
fig_retail = plotly_fig(complete_merge_df, "retailing", 'Retail')
py.iplot(fig_retail, filename='Just Score vs EPA Penalty Retail')

In [43]:
fig_fin = plotly_fig(complete_merge_df, "financial services", 'Financial Services')
py.iplot(fig_fin, filename='Just Score vs EPA Financial Services')